#!/bin/bash
# ---------------------------------------------------------------------------
# This script installs files and services specific to the project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/autobackup-service
#
# ---------------------------------------------------------------------------

PACKAGES="rsnapshot rsync"
PROJECT="autobackup"

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

install_packages() {
  if [ -n "$PACKAGES" ] && check_packages $PACKAGES; then
    echo -e "[INFO] installing additional packages" 2>&1
    apt-get update
    apt-get -y --no-upgrade install $PACKAGES
  fi
}

# --- install specific files   ----------------------------------------------

install_files() {
  echo -e "[INFO] installing project files" 2>&1

  rand="$RANDOM"
  if [ -f "/etc/$PROJECT.conf" ]; then
    # save current configuration
    mv "/etc/$PROJECT.conf" "/etc/$PROJECT.conf.$rand"
  fi

  for f in `find $(dirname "$0")/../files/ -type f -not -name "*.pyc"`; do
    target="${f#*files}"
    target_dir="${target%/*}"
    [ ! -d "$target_dir" ] && mkdir -p "$target_dir"
    cp "$f" "$target"
    chown root:root "$target"
  done

  chmod 755 "/usr/local/sbin/$PROJECT"
  chmod 644  "/etc/$PROJECT.conf"
  chmod 644 "/etc/udev/rules.d/99-$PROJECT.rules"
  chmod 644 "/etc/systemd/system/$PROJECT@.service"

  # restore old configuration
  if [ -f "/etc/$PROJECT.conf.$rand" ]; then
    mv -f "/etc/$PROJECT.conf" "/etc/$PROJECT.conf.new"
    mv "/etc/$PROJECT.conf.$rand" "/etc/$PROJECT.conf"
    echo -e "[INFO] new version of configuration file saved to: /etc/$PROJECT.conf.new" 2>&1
  fi
}

# --- configure system   ----------------------------------------------------

configure_system() {
  :
}

# --- activate service   ----------------------------------------------------

enable_services() {
  :
}

# --- main program   --------------------------------------------------------

install_packages
install_files
configure_system
enable_services

echo "[INFO] installation completed"
echo "[INFO] Please edit /etc/autobackup.conf, /etc/rsnapshot.conf"
